"""expand_candidate_profile

Revision ID: 8594e82b27ee
Revises: dc29a17e4377
Create Date: 2026-04-05 11:38:54.243140

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8594e82b27ee'
down_revision: Union[str, Sequence[str], None] = 'dc29a17e4377'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidate_profiles', sa.Column('pqe_is_range', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('candidate_profiles', sa.Column('pqe_range_min', sa.Integer(), nullable=True))
    op.add_column('candidate_profiles', sa.Column('pqe_range_max', sa.Integer(), nullable=True))
    op.add_column('candidate_profiles', sa.Column('firm_tier', sa.String(length=64), nullable=True))
    op.add_column('candidate_profiles', sa.Column('university', sa.String(length=128), nullable=True))
    op.add_column('candidate_profiles', sa.Column('preferred_locations', postgresql.ARRAY(sa.String(length=64)), nullable=True))
    op.add_column('candidate_profiles', sa.Column('salary_min_k', sa.Integer(), nullable=True))
    op.add_column('candidate_profiles', sa.Column('salary_max_k', sa.Integer(), nullable=True))
    op.add_column('candidate_profiles', sa.Column('salary_disclosed', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('candidate_profiles', sa.Column('languages', postgresql.ARRAY(sa.String(length=64)), nullable=True))
    op.add_column('candidate_profiles', sa.Column('employment_types', postgresql.ARRAY(sa.String(length=64)), nullable=True))
    op.add_column('candidate_profiles', sa.Column('work_arrangements', postgresql.ARRAY(sa.String(length=64)), nullable=True))
    op.add_column('candidate_profiles', sa.Column('excluded_firms', postgresql.ARRAY(sa.String(length=128)), nullable=True))
    op.add_column('candidate_profiles', sa.Column('preferred_destinations', postgresql.ARRAY(sa.String(length=128)), nullable=True))
    op.add_column('candidate_profiles', sa.Column('specific_firm_preference', sa.String(length=255), nullable=True))
    op.add_column('candidate_profiles', sa.Column('verification_professional_email', sa.String(length=320), nullable=True))
    op.add_column('candidate_profiles', sa.Column('linkedin_url', sa.String(length=512), nullable=True))
    op.add_column('candidate_profiles', sa.Column('open_to_roles', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    op.add_column('candidate_profiles', sa.Column('profile_verified', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('candidate_profiles', 'profile_verified')
    op.drop_column('candidate_profiles', 'open_to_roles')
    op.drop_column('candidate_profiles', 'linkedin_url')
    op.drop_column('candidate_profiles', 'verification_professional_email')
    op.drop_column('candidate_profiles', 'specific_firm_preference')
    op.drop_column('candidate_profiles', 'preferred_destinations')
    op.drop_column('candidate_profiles', 'excluded_firms')
    op.drop_column('candidate_profiles', 'work_arrangements')
    op.drop_column('candidate_profiles', 'employment_types')
    op.drop_column('candidate_profiles', 'languages')
    op.drop_column('candidate_profiles', 'salary_disclosed')
    op.drop_column('candidate_profiles', 'salary_max_k')
    op.drop_column('candidate_profiles', 'salary_min_k')
    op.drop_column('candidate_profiles', 'preferred_locations')
    op.drop_column('candidate_profiles', 'university')
    op.drop_column('candidate_profiles', 'firm_tier')
    op.drop_column('candidate_profiles', 'pqe_range_max')
    op.drop_column('candidate_profiles', 'pqe_range_min')
    op.drop_column('candidate_profiles', 'pqe_is_range')
    # ### end Alembic commands ###
