"""candidate_structured_career_fields

Revision ID: a38f8130978d
Revises: 8594e82b27ee
Create Date: 2026-04-05 11:58:43.018577

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a38f8130978d'
down_revision: Union[str, Sequence[str], None] = '8594e82b27ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidate_profiles', sa.Column('title', sa.String(length=128), nullable=True))
    op.add_column('candidate_profiles', sa.Column('current_firm', sa.String(length=255), nullable=True))
    op.add_column('candidate_profiles', sa.Column('former_firms', sa.Text(), nullable=True))
    op.add_column('candidate_profiles', sa.Column('trainee_firm', sa.String(length=255), nullable=True))
    op.add_column('candidate_profiles', sa.Column('primary_admission', sa.String(length=32), nullable=True))
    op.add_column('candidate_profiles', sa.Column('admission_year', sa.Integer(), nullable=True))
    op.add_column('candidate_profiles', sa.Column('source_profile_url', sa.String(length=1024), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('candidate_profiles', 'source_profile_url')
    op.drop_column('candidate_profiles', 'admission_year')
    op.drop_column('candidate_profiles', 'primary_admission')
    op.drop_column('candidate_profiles', 'trainee_firm')
    op.drop_column('candidate_profiles', 'former_firms')
    op.drop_column('candidate_profiles', 'current_firm')
    op.drop_column('candidate_profiles', 'title')
    # ### end Alembic commands ###
