"""firm_hiring_partners_band

Revision ID: ea5d8bedad29
Revises: a38f8130978d
Create Date: 2026-04-05 12:22:33.210846

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ea5d8bedad29'
down_revision: Union[str, Sequence[str], None] = 'a38f8130978d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('firm_profiles', sa.Column('hiring_partners_band', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('firm_profiles', 'hiring_partners_band')
    # ### end Alembic commands ###
